services:
  admin.parameters:
    class: WebEtDesign\ParameterBundle\Admin\ParameterAdmin
    arguments: [~, WebEtDesign\ParameterBundle\Entity\Parameter, WebEtDesign\ParameterBundle\Controller\ParameterAdminController]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Admin, label: Parameter, icon: '<i class="fa fa-cogs"></i>' }
    public: true
    calls:
      - [setTranslationDomain, ['WebEtDesignParameterBundle']]
      - [setParameterManager, ['@WebEtDesign\ParameterBundle\Model\ParameterManagerInterface']]
