services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  admin.parameters:
    class: WebEtDesign\ParameterBundle\Admin\ParameterAdmin
    tags:
      - { name: sonata.admin, model_class: WebEtDesign\ParameterBundle\Entity\Parameter , controller: WebEtDesign\ParameterBundle\Controller\ParameterAdminController, manager_type: orm, group: Admin, label: Parameter, icon: '<i class="fa fa-cogs"></i>' }
    public: true
    calls:
      - [setTranslationDomain, ['WebEtDesignParameterBundle']]
      - [setParameterManager, ['@WebEtDesign\ParameterBundle\Model\ParameterManagerInterface']]
