services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  WebEtDesign\ParameterBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  webetdesign.parameter:
    class: WebEtDesign\ParameterBundle\Service\ParameterService
    public: true

  WebEtDesign\ParameterBundle\Service\ParameterService:
    bind:
      $parametersType: '%parameter.types%'

  WebEtDesign\ParameterBundle\Command\FixtureCommand:
    bind:
      $parameterFixtures: '%parameter.fixtures%'